### ISSUE TITLE
Typo in StabilizerInterface

### ISSUE THREAD

**Issue by hiimanget** [nadeemabdulhamid/PeerBase#4]
[Link](https://github.com/nadeemabdulhamid/PeerBase/blob/aab73e2526512522c7d94752f948d89fac2952ad/src-java/peerbase/StabilizerInterface.java#L37)

looks should be `stabilize()`

**Comment by nadeemabdulhamid** [comment]
Yes, I think you're right about that. For some reason I even wrote the example concrete class in util/SimplePingStabilizer.java and didn't notice the awkwardness of the name!
